config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts 
  resources :friendships
  post 'posts/add_friends' => 'posts#add_friends'
  get '/user_list' => 'posts#user_list'
  root 'posts#index'

end

app/models/friend.rb
class Friend < ActiveRecord::Base
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
    belongs_to :friend, :class_name => "User"
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
 class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :friendships
  has_many :friends , :through => :friendships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	def create
		@friendships = current_user.friendships.create(:friend_id => params[:friend_id])
		if @friendships.save
			flash[:notice] = "Added friend."
			redirect_to :back
		else 
			flash[:error] = "not created"
			redirect_to :back
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  def index
    @user = User.all.where.not( :id => current_user.id )
    @posts = Post.where("user_id IN (?)", current_user.friends.pluck(:id))
    @current_user_post = Post.where(:user_id => current_user.id)
    @post = Post.new
  end
  
  def add_friends
      @friends = Friend.create(:user_id => params[:friend][:id])
      redirect_to '/'
  end

  def user_list
      @users = current_user
      @user = User.all.where.not( :id => current_user.id )
  end
  def show
  end
 
  def new
    @post = Post.new
  end
 
  def edit
  end
 
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end
 
  def update
 
    if @post.update(post_params)
      redirect_to posts_path
    else
      render 'edit'
    end
  end
 
  def destroy
    @post.destroy
 
    redirect_to posts_path
  end
 
  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:text , :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facebook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
		<p class="notice"><%= notice %></p>
    	<p class="alert"><%= alert %></p>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
 
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h><b>posts</b></h>
<a href="/user_list">User List</a>
<p>
followers : <% current_user.friends.count %>

<p><%= current_user.email %></p>
<% @posts.each do |post| %>
	<p><%= post.user.email if post.user.present? %> :<%= post.text %>&nbsp;<td><%= link_to 'Edit', edit_post_path(post) %></td><td> <td><%= link_to 'Destroy', post_path(post),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td></td></p>
<% end %>
<% @current_user_post.each do |post| %>
	<p><%= post.user.email if post.user.present? %> :<%= post.text %>&nbsp;<td><%= link_to 'Edit', edit_post_path(post) %></td><td> <td><%= link_to 'Destroy', post_path(post),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td></td></p>
<% end %>
</p>
<p>
<a href="/posts/new">new post</a>
</p>
<p><%= link_to "Sign out",destroy_user_session_path,method: :delete, class: "profile-dropdown" %></p>

app/views/posts/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/user_list.html.erb
<p><h>friends list</h></p>
<% if @users.friends.present? %>
	<% @users.friends.each do |friend| %>
 	<p><%= friend.email %></p>
	<% end %>
<% else %>
 <p>no friends there...</p>
<% end %>
<br><br>
<p><h>Add friend</h></p>
<% @user.each do |user| %>
	<p><%= user.email %>&nbsp;<%= link_to "Add friend", friendships_path(:friend_id => user), :method => :post %></p>
 <%# end %>
<% end %>